[package]
name = "3d-scene"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.2", features=["jpeg"]  }
bevy_flycam = "0.11.0"
rand = "0.8.5"
